name: Scrape

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Cache DID database
        uses: actions/cache@v4
        with:
          key: did-v1-${{ steps.date.outputs.date }}
          restore-keys: did-v1-
          path: did.sqlite3

      - name: Run DID exporter
        run: bun run ./scripts/export-dids.ts

      - name: Run Markdown generator
        run: bun run ./scripts/generate-markdown.ts

      - name: Push to repository
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

          git add README.md
          git commit -m "update: $(date --iso-8601=seconds)" || exit 0
          git push
